name: "Biochemical"
model_name: 'model-biochemical-llc'
model_type: 'LLC'
epochs: 1000
patience: 200
opt: 'Adam'
log: 10
t_span: [0,1]
t_eval_steps: 2000
seed: 42
pytorch_seed: 0
device: 'cuda:0'
input_range: [0, 1]
in_dim: 1
atol: 0.00001
rtol: 0.001
adjoint: True
message_passing: False
include_time: False
horizon: 15
history: 1
preprocess_data: False
stride: 1
storage: "journal"
save_cache_data: True
n_iter: 1
num_samples: -1
predict_deriv: True
data_folder: './data_ic1_deriv'
criterion: "MAE"
method: "dopri5"
integration_kwargs:
  F: 1.0
  B: 0.5
  R: 0.5
search_space:
  n_hidden_layers_g0: [1, 2]
  hidden_dims_g0: [8, 64]
  af_g0: ["relu", "softplus", "tanh"]
  drop_p_g0: [0.0]

  n_hidden_layers_g1: [1, 2]
  hidden_dims_g1: [8, 64]
  af_g1: ["relu", "softplus", "tanh"]
  drop_p_g1: [0.0]

  n_hidden_layers_g2: [1, 2]
  hidden_dims_g2: [8, 64]
  af_g2: ["relu", "softplus", "tanh"]
  drop_p_g2: [0.0]

  n_hidden_layers_h_net: [1, 2]
  hidden_dims_h_net: [8, 64]
  af_h_net: ["relu", "softplus", "tanh"]
  drop_p_h_net: [0.0]

  lr: [0.0005, 0.05]
  batch_size: [16, 32, 64]

  lamb: [0., 0.01]