name: "Epidemics"
model_name: 'model-epidemics-mpnn'
model_type: 'MPNN'
epochs: 500
patience: 100
opt: 'Adam'
log: 1
t_span: [0,1]
t_eval_steps: 300
seed: 123
pytorch_seed: 0
device: 'cuda:0'
input_range: [0, 1]
in_dim: 1
atol: 0.00001
rtol: 0.001
adjoint: True
message_passing: False
include_time: False
horizon: 15
history: 1
preprocess_data: False
stride: 5
storage: "journal"
save_cache_data: True
n_iter: 3
num_samples: -1
predict_deriv: True
data_folder: './data_deriv'
criterion: "MAE"
method: "dopri5"
integration_kwargs:
  B: 0.5
  R: 0.5
search_space:
  n_hidden_layers_g_net: [1, 2]
  n_hidden_layers_h_net: [1, 2]
  hidden_dims_g_net: [8, 64]
  hidden_dims_h_net: [8, 64]
  af_g_net: ["relu", "softplus", "tanh"]
  af_h_net: ["relu", "softplus", "tanh"]
  drop_p_g_net: [0.0001, 0.5]
  drop_p_h_net: [0.0001, 0.5]
  lr: [0.0005, 0.05]
  batch_size: [16, 32]
