adjoint: true
atol: 1.0e-05
criterion: MAE
data_folder: ./data_ic5_deriv_gkan
device: cuda:1
epochs: 500
history: 1
horizon: 15
in_dim: 1
include_time: false
input_range:
- 0
- 1
integration_kwargs:
  B: 0.5
  C: 0.8
  R: 0.3
log: 1
message_passing: false
method: dopri5
model_name: model-neuronal-gkan
model_type: GKAN
n_iter: 5
name: Neuronal
num_samples: -1
opt: Adam
patience: 100
predict_deriv: true
preprocess_data: false
pytorch_seed: 0
rtol: 0.001
save_cache_data: true
search_space:
  batch_size:
  - 16
  - 32
  grid_size_g_net:
  - 5
  - 15
  grid_size_h_net:
  - 5
  - 15
  hidden_dim_g_net:
  - 1
  - 5
  hidden_dim_h_net:
  - 1
  - 5
  lamb:
  - 1.0
  lamb_g_net:
  - 1.0e-06
  - 0.01
  lamb_h_net:
  - 1.0e-06
  - 0.01
  lr:
  - 0.0005
  - 0.05
  mu_1_g_net:
  - 0.5
  - 1.0
  mu_1_h_net:
  - 0.5
  - 1.0
  mu_2_g_net:
  - 0.5
  - 1.0
  mu_2_h_net:
  - 0.5
  - 1.0
  range_limit_g_net:
  - 1
  - 10
  range_limit_h_net:
  - 1
  - 10
  spline_order_g_net:
  - 1
  - 3
  spline_order_h_net:
  - 1
  - 3
  use_orig_reg:
  - true
  - false
seed: 42
storage: journal
stride: 5
t_eval_steps: 300
t_span:
- 0
- 1
