adjoint: true
atol: 1.0e-05
criterion: MAE
data_folder: ./data_ic1_deriv_gkan
device: cuda:0
epochs: 1000
history: 1
horizon: 15
in_dim: 1
include_time: false
input_range:
- 0
- 1
integration_kwargs:
  B: 0.5
  F: 1.0
  R: 0.5
log: 10
message_passing: false
method: dopri5
model_name: model-biochemical-gkan
model_type: GKAN
n_iter: 1
name: Biochemical
num_samples: -1
opt: Adam
patience: 200
predict_deriv: true
preprocess_data: false
pytorch_seed: 0
rtol: 0.001
save_cache_data: true
search_space:
  batch_size:
  - 16
  - 32
  - 64
  grid_size_g_net:
  - 5
  - 20
  grid_size_h_net:
  - 5
  - 20
  hidden_dim_g_net:
  - 1
  - 6
  hidden_dim_h_net:
  - 1
  - 6
  lamb:
  - 1.0
  lamb_g_net:
  - 1.0e-06
  - 1.0
  lamb_h_net:
  - 1.0e-06
  - 1.0
  lr:
  - 0.0005
  - 0.05
  mu_1_g_net:
  - 0.1
  - 1.0
  mu_1_h_net:
  - 0.1
  - 1.0
  mu_2_g_net:
  - 0.1
  - 1.0
  mu_2_h_net:
  - 0.1
  - 1.0
  range_limit_g_net:
  - 1
  - 10
  range_limit_h_net:
  - 1
  - 10
  spline_order_g_net:
  - 1
  - 3
  spline_order_h_net:
  - 1
  - 3
  use_orig_reg:
  - true
seed: 42
storage: journal
stride: 1
t_eval_steps: 2000
t_span:
- 0
- 1
