dynamics: 'Kuramoto'
model_name: 'model-kuramoto-grid'
epochs: 500
patience: 100
opt: 'Adam'
log: 10 
t_span: [0,1]
t_eval_steps: 150
seed: 0
noise_strengths: []
device: 'cpu'
input_range: [0, 6.28318530718]
reg_loss: true
vmin: -5
vmax: 5
g_hidden_layers: [2,1,1]
h_hidden_layers: [2,1]
integration_kwargs:
  w: 2.
  R: 1.