name: "metrla"
model_name: "model-metrla-mpnn"
model_type: 'MPNN'
epochs: 500
patience: 200
opt: 'Adam'
log: 10
seed: 42
pytorch_seed: 0
device: 'cuda'
in_dim: 1
n_iter: 3
num_samples: 30
data_folder: './data'
R: 1
method: 'dopri5'
message_passing: False
search_space:
  n_hidden_layers_g_net: [1, 2]
  n_hidden_layers_h_net: [1, 2]
  hidden_dims_g_net: [16, 64]
  hidden_dims_h_net: [16, 64]
  af_g_net: ["relu", "sigmoid", "softplus"]
  af_h_net: ["relu", "sigmoid", "softplus"]
  drop_p_g_net: [0.0001, 0.5]
  drop_p_h_net: [0.0001, 0.5]
  lr: [0.0001, 0.05]
  batch_size: [32]