name: "metrla"
model_name: "model-metrla-mpnn"
model_type: 'MPNN'
epochs: 100
patience: 25
opt: 'Adam'
log: 1
seed: 42
pytorch_seed: 0
device: 'cuda'
n_iter: -1
num_samples: -1
data_folder: './data'
R: 1
method: 'dopri5'
message_passing: True
include_time: True
criterion: 'MAE'
adjoint: True
horizon: 12
atol: 0.00001
rtol: 0.001
search_space:
  n_hidden_layers_g_net: [1, 2]
  n_hidden_layers_h_net: [1, 2]
  hidden_dims_g_net: [32, 64]
  hidden_dims_h_net: [32, 64]
  af_g_net: ["tanh", "relu", "softplus"]
  af_h_net: ["tanh", "relu", "softplus"]
  drop_p_g_net: [0.0001, 0.05]
  drop_p_h_net: [0.0001, 0.05]
  lr: [0.0001, 0.05]
  batch_size: [16, 32]