name: "Epidemics"
model_name: 'model-epidemics-mpnn'
model_type: 'MPNN'
epochs: 10
patience: 200
opt: 'Adam'
log: 1 
t_span: [0,1]
t_eval_steps: 300
seed: 42
pytorch_seed: 0
device: 'cuda'
input_range: [0, 1]
in_dim: 1
method: 'dopri5'
message_passing: True
atol: 0.00001
rtol: 0.001
adjoint: True
include_time: False
criterion: 'MSE'
n_iter: 3
num_samples: -1
data_folder: './data'
horizon: 18
integration_kwargs:
  B: 0.5
  R: 0.5
search_space:
  n_hidden_layers_g_net: [1, 2]
  n_hidden_layers_h_net: [1, 2]
  hidden_dims_g_net: [16, 64]
  hidden_dims_h_net: [16, 64]
  af_g_net: ["relu", "tanh", "softplus"]
  af_h_net: ["relu", "tanh", "softplus"]
  drop_p_g_net: [0.0001, 0.5]
  drop_p_h_net: [0.0001, 0.5]
  lr: [0.001, 0.05]
  batch_size: [32, 64]