name: "metrla"
model_name: "model-metrla-gkan"
model_type: 'GKAN'
epochs: 100
patience: 30
opt: 'Adam'
log: 10
seed: 42
pytorch_seed: 0
device: 'cuda'
in_dim: 1
n_iter: 119
num_samples: 96
data_folder: './data'
R: 1
method: 'midpoint'
message_passing: False
include_time: False
criterion: 'MAE'
adjoint: False
search_space:
  grid_size_h_net: [5, 10]
  grid_size_g_net: [5, 10]
  spline_order_h_net: [1, 3]
  spline_order_g_net: [1, 3]
  range_limit_h_net: [1, 3]
  range_limit_g_net: [1, 3]
  hidden_dim_h_net: [1, 5]
  hidden_dim_g_net: [1, 5]
  lamb_g_net: [0.000001, 0.01]
  lamb_h_net: [0.000001, 0.01]
  mu_1_g_net: [0.5, 1.0]
  mu_2_g_net: [0.5, 1.0]
  mu_1_h_net: [0.5, 1.0]
  mu_2_h_net: [0.5, 1.0]
  lr: [0.0001, 0.05]
  use_orig_reg: [False, True]
  lamb: [0.]
  batch_size: [32, 64]