dynamics: 'Kuramoto'
model_name: 'model-kuramoto-mpnn'
model_type: 'MPNN'
epochs: 400
patience: 150
opt: 'Adam'
log: 10 
t_span: [0,1]
t_eval_steps: 300
seed: 42
noise_strengths: []
device: 'cuda'
input_range: [0, 6.28318530718]
in_dim: 1
search_space:
  n_hidden_layers_g_net: [1]
  n_hidden_layers_h_net: [1]
  hidden_dims_g_net: [16, 64]
  hidden_dims_h_net: [16, 64]
  lr: [0.01, 0.05]
  batch_size: [16, 120]
  stride: [16, 120]
n_iter: 2
integration_kwargs:
  w: 2.
  R: 0.5