dynamics: 'Kuramoto'
model_name: "model-kuramoto-gkan"
model_type: 'GKAN'
epochs: 400
patience: 200
opt: 'Adam'
log: 10 
t_span: [0,1]
t_eval_steps: 300
seed: 42
noise_strengths: []
device: 'cuda'
input_range: [0, 6.28318530718]
in_dim: 1
search_space:
  grid_size_h_net: [5, 10]
  grid_size_g_net: [5, 10]
  spline_order_h_net: [1, 3]
  spline_order_g_net: [1, 3]
  range_limit_h_net: [5, 10]
  range_limit_g_net: [5, 10]
  hidden_dim_h_net: [1, 3]
  hidden_dim_g_net: [1, 3]
  lamb_g_net: [0.0001, 0.01]
  lamb_h_net: [0.0001, 0.01]
  lr: [0.001, 0.05]
  use_orig_reg: [True, False]
  lamb: [1.]
  batch_size: [16, 120]
  stride: [16, 120]
n_iter: 2
integration_kwargs:
  w: 2.
  R: 0.5