dynamics: "Epidemics"
model_name: "model-epidemics-gkan"
model_type: 'GKAN'
epochs: 700
patience: 200
opt: 'Adam'
log: 10
t_span: [0,1]
t_eval_steps: 500
seed: 42
pytorch_seed: 0
device: 'cuda'
input_range: [0, 1]
in_dim: 1
n_iter: 3
num_samples: 50
data_folder: './data'
R: 1
method: 'dopri5'
message_passing: False
search_space:
  grid_size_h_net: [5, 10]
  grid_size_g_net: [5, 10]
  spline_order_h_net: [1, 3]
  spline_order_g_net: [1, 3]
  range_limit_h_net: [1, 3]
  range_limit_g_net: [1, 3]
  hidden_dim_h_net: [1]
  hidden_dim_g_net: [1, 2]
  lamb_g_net: [0.000001, 0.01]
  lamb_h_net: [0.000001, 0.01]
  mu_1_g_net: [0.5, 1.0]
  mu_2_g_net: [0.5, 1.0]
  mu_1_h_net: [0.5, 1.0]
  mu_2_h_net: [0.5, 1.0]
  lr: [0.001, 0.05]
  use_orig_reg: [False]
  lamb: [0.]
  batch_size: [32,64]
integration_kwargs:
  B: 0.5
  R: 0.5