name: 'Kuramoto'
model_name: "model-kuramoto-gkan"
model_type: 'GKAN'
epochs: 500
patience: 200
opt: 'Adam'
log: 10
t_span: [0,1]
t_eval_steps: 300
seed: 42
pytorch_seed: 0
device: 'cuda'
input_range: [0, 6.28318530718]
in_dim: 1
message_passing: True
include_time: False
atol: 0.000001
rtol: 0.001
adjoint: True
search_space:
  grid_size_h_net: [5, 10]
  grid_size_g_net: [5, 10]
  spline_order_h_net: [1, 3]
  spline_order_g_net: [1, 3]
  range_limit_h_net: [5, 10]
  range_limit_g_net: [5, 10]
  hidden_dim_h_net: [1, 3]
  hidden_dim_g_net: [1, 3]
  lamb_g_net: [0.000001, 0.01]
  lamb_h_net: [0.000001, 0.01]
  lr: [0.0001, 0.05]
  use_orig_reg: [True, False]
  mu_1_g_net: [0.5, 1.0]
  mu_2_g_net: [0.5, 1.0]
  mu_1_h_net: [0.5, 1.0]
  mu_2_h_net: [0.5, 1.0]
  lamb: [1.]
  batch_size: [32, 64]
n_iter: 2
num_samples: 30
data_folder: './data'
integration_kwargs:
  w: 2.
  R: 0.5