dynamics: 'Kuramoto'
model_name: 'model-kuramoto-grid-optuna'
epochs: 1000
patience: 250
opt: 'Adam'
log: 10 
t_span: [0,1]
t_eval_steps: 300
seed: 42
noise_strengths: []
device: 'cpu'
input_range: [0, 6.28318530718]
reg_loss: true
grid_size: [5, 7]
spline_order: [2, 3]
range_limit: [5]
lr: [0.01, 0.05]
lamb: [0.001]
mu_1: [1.]
mu_2: [1.]
use_orig_reg: [True]
integration_kwargs:
  w: 2.
  R: 1.