dynamics: "Epidemics"
model_name: "model-epidemics-gkan"
model_type: 'GKAN'
epochs: 1000
patience: 200
opt: 'Adam'
log: 10
t_span: [0,1]
t_eval_steps: 300
seed: 42
pytorch_seed: 43
device: 'cpu'
input_range: [0, 1]
in_dim: 1
n_iter: 2
integration_kwargs:
  B: 0.5
  R: 0.5