root: './data'
name: 'kuramoto'
dynamics: 'Kuramoto'
model_name: 'model-kuramoto'
epochs: 200
patience: 30
opt: 'Adam'
log: 10 
time_steps: 1000
num_samples: 1000
step_size: 0.001
min_sample_distance: 1
seed: 0
regular_samples: true
add_noise_target: false
noise_strengths: []
add_noise_input: false
in_noise_dim: 0
device: 'cuda'
input_range: [0, 1]
integration_kwargs:
  w: 0.5
  R: 1.