dynamics: 'Kuramoto'
model_name: 'model-kuramoto-grid-gcn'
model_type: 'GCN'
epochs: 100
patience: 200
opt: 'Adam'
log: 10 
t_span: [0,1]
t_eval_steps: 300
seed: 42
noise_strengths: []
device: 'cpu'
input_range: [0, 6.28318530718]
reg_loss: true
in_dim: 1
search_space:
  hidden_dim: [8, 32]
  lr: [0.001, 0.01]
n_iter: 1
integration_kwargs:
  w: 2.
  R: 1.