dynamics: "Epidemics"
model_name: "model-epidemics-gkan"
model_type: 'GKAN'
epochs: 500
patience: 200
opt: 'Adam'
log: 10
t_span: [0,1]
t_eval_steps: 900
seed: 42
pytorch_seed: 43
device: 'cuda'
input_range: [0, 1]
in_dim: 1
n_iter: 2
loss_temp: 10
search_space:
  grid_size_h_net: [5, 10]
  grid_size_g_net: [5, 10]
  spline_order_h_net: [1, 3]
  spline_order_g_net: [1, 3]
  range_limit_h_net: [1, 2]
  range_limit_g_net: [1, 2]
  hidden_dim_h_net: [1, 2]
  hidden_dim_g_net: [1, 2]
  lamb_g_net: [0.0]
  lamb_h_net: [0.0]
  lr: [0.001, 0.01]
  use_orig_reg: [False]
  lamb: [0.]
  batch_size: [100]
  stride: [100,50]
integration_kwargs:
  B: 0.5
  R: 0.5