dynamics: 'Kuramoto'
model_name: 'model-kuramoto-grid-2-3-1(2)'
epochs: 700
patience: 200
opt: 'Adam'
log: 10 
t_span: [0,1]
t_eval_steps: 300
seed: 42
noise_strengths: []
device: 'cuda'
input_range: [0, 6.28318530718]
reg_loss: true
grid_size: [3, 10]
spline_order: [2, 4]
range_limit: [5, 7]
lr: [0.01, 0.1]
lmbd_g: [0., 0.01]
lmbd_h: [0., 0.01]
mu_1: [1.]
mu_2: [1.]
use_orig_reg: [False, True]
n_iter: 2
integration_kwargs:
  w: 2.
  R: 1.