name: "metrla"
model_name: "model-metrla-mpnn"
model_type: 'MPNN'
epochs: 100
patience: 30
opt: 'Adam'
log: 10
seed: 42
pytorch_seed: 0
device: 'cuda'
in_dim: 1
n_iter: 119
num_samples: 96
data_folder: './data'
R: 1
method: 'dopri5'
message_passing: True
include_time: True
criterion: 'MAE'
adjoint: True
horizon: 36
atol: 0.0001
rtol: 0.001
search_space:
  n_hidden_layers_g_net: [1]
  n_hidden_layers_h_net: [1]
  hidden_dims_g_net: [16, 64]
  hidden_dims_h_net: [16, 64]
  af_g_net: ["relu", "sigmoid", "softplus", "tanh"]
  af_h_net: ["relu", "sigmoid", "softplus", "tanh"]
  drop_p_g_net: [0.0001, 0.5]
  drop_p_h_net: [0.0001, 0.5]
  lr: [0.0001, 0.05]
  batch_size: [32, 64]