name: "metrla"
model_name: "model-metrla-mpnn"
model_type: 'MPNN'
epochs: 5
patience: 25
opt: 'Adam'
log: 1
seed: 42
pytorch_seed: 0
device: 'cuda'
in_dim: 1
n_iter: 2
num_samples: -1
data_folder: './data'
R: 1
method: 'dopri5'
message_passing: True
include_time: True
criterion: 'MAE'
adjoint: True
horizon: 287
atol: 0.00001
rtol: 0.001
search_space:
  n_hidden_layers_g_net: [1]
  n_hidden_layers_h_net: [1]
  hidden_dims_g_net: [64]
  hidden_dims_h_net: [64]
  af_g_net: ["tanh"]
  af_h_net: ["tanh"]
  drop_p_g_net: [0.0001]
  drop_p_h_net: [0.0001]
  lr: [0.0001, 0.05]
  batch_size: [1]