criterion: MAE
data_folder: ./data_real_epid_covid_scaled
device: cuda:0
epochs: 1000
in_dim: 1
include_time: false
log: 10
message_passing: false
model_name: model-real-epid-llc
model_type: LLC
name: RealEpid
num_samples: -1
opt: Adam
patience: 300
predict_deriv: true
preprocess_data: false
pytorch_seed: 0
save_cache_data: true
scale: true
seed: 42
storage: journal
stride: 1
scale_range:
- -1
- 1
search_space:
  n_hidden_layers_g0: [1, 2]
  hidden_dims_g0: [8, 64]
  af_g0: ["relu", "softplus", "tanh"]
  drop_p_g0: [0.0]

  n_hidden_layers_g1: [1, 2]
  hidden_dims_g1: [8, 64]
  af_g1: ["relu", "softplus", "tanh"]
  drop_p_g1: [0.0]

  n_hidden_layers_g2: [1, 2]
  hidden_dims_g2: [8, 64]
  af_g2: ["relu", "softplus", "tanh"]
  drop_p_g2: [0.0]

  n_hidden_layers_h_net: [1, 2]
  hidden_dims_h_net: [8, 64]
  af_h_net: ["relu", "softplus", "tanh"]
  drop_p_h_net: [0.0]

  lr: [0.0005, 0.05]
  batch_size: [16, 32, 64]

  lamb: [0., 0.01]