criterion: MAE
data_folder: ./data_real_epid_covid_scaled09
device: cuda:0
epochs: 1000
in_dim: 1
include_time: false
log: 10
message_passing: false
model_name: model-real-epid-gkan
model_type: GKAN
name: RealEpid
num_samples: -1
opt: Adam
patience: 300
predict_deriv: true
preprocess_data: false
pytorch_seed: 0
save_cache_data: true
scale: true
scale_range:
- -1
- 1
search_space:
  batch_size:
  - 16
  - 32
  - 64
  grid_size_g_net:
  - 5
  - 20
  grid_size_h_net:
  - 5
  - 20
  hidden_dim_g_net:
  - 1
  - 6
  hidden_dim_h_net:
  - 1
  - 6
  lamb:
  - 1.0
  lamb_g_net:
  - 1.0e-06
  - 1.0
  lamb_h_net:
  - 1.0e-06
  - 1.0
  lr:
  - 0.0005
  - 0.05
  mu_1_g_net:
  - 0.1
  - 1.0
  mu_1_h_net:
  - 0.1
  - 1.0
  mu_2_g_net:
  - 0.1
  - 1.0
  mu_2_h_net:
  - 0.1
  - 1.0
  n_hidden_layers_g_net:
  - 1
  - 2
  n_hidden_layers_h_net:
  - 1
  - 2
  range_limit_g_net:
  - 1
  - 5
  range_limit_h_net:
  - 1
  - 5
  spline_order_g_net:
  - 1
  - 3
  spline_order_h_net:
  - 1
  - 3
  use_orig_reg:
  - true
seed: 42
storage: journal
stride: 1
tr_perc: 0.9